### ISSUE TITLE
0.1.0-rc3: crash in go-streamrpc

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#132]
I had it running and just realised that it crashed:

```
2019-03-05T10:17:52+01:00 [ERRO][backup_system][repl]: filesystem replication encountered a filesystem-specific error err="step zfsintern/Users@zrepl_20190305_091747_000 (full) failed: handler error with unconsumed input stream: zfs exited with error: exit status 1\nstderr:\ncannot create 'zfssnaps': missing dataset name\n" invocation="20"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x148233c]

goroutine 14 [running]:
github.com/zrepl/zrepl/daemon/transport.DoHandshakeVersion(0x0, 0x0, 0xbf17ad9292d00e28, 0xad81100f5f9, 0x1bd6500, 0x1, 0x1bd6500, 0xc0003f6300)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/transport/handshake.go:118 +0x19c
github.com/zrepl/zrepl/daemon/transport.DoHandshakeCurrentVersion(...)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/transport/handshake.go:105
github.com/zrepl/zrepl/daemon/transport/connecter.HandshakeConnecter.Connect(0x1767140, 0xc000214640, 0x1774da0, 0xc000094c00, 0x14, 0x0, 0x0, 0x0)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/transport/connecter/connecter.go:28 +0xdb
github.com/zrepl/zrepl/vendor/github.com/problame/go-streamrpc.(*connMan).getConn(0xc000130048, 0x1774da0, 0xc000094c00, 0x1bd5c01, 0x0, 0x0, 0x0)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/vendor/github.com/problame/go-streamrpc/client.go:96 +0x230
github.com/zrepl/zrepl/vendor/github.com/problame/go-streamrpc.(*Client).RequestReply(0xc000130040, 0x1774da0, 0xc000094c00, 0x169cf46, 0x7, 0xc000094e70, 0x176d460, 0xc000173270, 0x16a8d52, 0x18, ...)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/vendor/github.com/problame/go-streamrpc/client.go:154 +0x68
github.com/zrepl/zrepl/endpoint.Remote.Receive(0xc000130040, 0x1774da0, 0xc000094c00, 0xc0003e1680, 0x176d460, 0xc000173270, 0x0, 0x0)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/endpoint/endpoint.go:426 +0x15e
github.com/zrepl/zrepl/replication/fsrep.(*ReplicationStep).doReplication(0xc0003bd080, 0x1774da0, 0xc000094c00, 0xc000174a10, 0x1d9c6e0, 0xc0002080e0, 0x1d9c950, 0xc000130040, 0x0, 0x0)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/replication/fsrep/fsfsm.go:428 +0x31d
github.com/zrepl/zrepl/replication/fsrep.(*ReplicationStep).Retry(0xc0003bd080, 0x1774da0, 0xc000094c00, 0xc000174a10, 0x1d9c6e0, 0xc0002080e0, 0x1d9c950, 0xc000130040, 0x100a68c, 0xc000696000)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/replication/fsrep/fsfsm.go:376 +0x125
github.com/zrepl/zrepl/replication/fsrep.(*Replication).Retry(0xc0000fc850, 0x1774da0, 0xc000094b10, 0xc000174a10, 0x1d9c6e0, 0xc0002080e0, 0x1d9c950, 0xc000130040, 0x0, 0x0)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/replication/fsrep/fsfsm.go:270 +0x369
github.com/zrepl/zrepl/replication.stateWorking(0x1774ce0, 0xc000130080, 0xc000174a10, 0x17761a0, 0xc0002080e0, 0x1775220, 0xc000130040, 0xc000208170, 0x16c6a18)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/replication/mainfsm.go:456 +0x320
github.com/zrepl/zrepl/replication.(*Replication).Drive(0xc000174a00, 0x1774ce0, 0xc000130080, 0x17761a0, 0xc0002080e0, 0x1775220, 0xc000130040)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/replication/mainfsm.go:159 +0x164
github.com/zrepl/zrepl/daemon/job.(*ActiveSide).do(0xc0000ef560, 0x1774ce0, 0xc000130000)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/job/active.go:379 +0x445
github.com/zrepl/zrepl/daemon/job.(*ActiveSide).Run(0xc0000ef560, 0x1774da0, 0xc000134510)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/job/active.go:263 +0x24c
github.com/zrepl/zrepl/daemon.(*jobs).start.func1(0xc000067600, 0x177bac0, 0xc000214a80, 0x1774fa0, 0xc0000ef560, 0x1774da0, 0xc000236420)
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/daemon.go:221 +0xdb
created by github.com/zrepl/zrepl/daemon.(*jobs).start
	/private/tmp/zrepl-20190304-8737-g2c5q/gopath/src/github.com/zrepl/zrepl/daemon/daemon.go:217 +0x527

```

**Comment by problame** [comment]
Seems like `go-streamrpc/client.go` returned a nil connection but also a nil error.

#111 replaces `go-streamrpc`, thus likely irrelevant for the next rc.

**Comment by problame** [comment]
Awaiting feedback as requested in https://github.com/zrepl/zrepl/pull/139#issuecomment-472586093
