### ISSUE TITLE
zrepl daemon crash on tcp source

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#348]
I've got zrepl (latest version built from git master) set up on 2 machines with a pull mode setup using tcp.
source system: latitude:
`Linux latitude.jbsnet.xyz 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
destination system: daytapod1:
`Linux daytapod1.jbsnet.xyz 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Both are running Ubuntu 20.04 with ZFS version 0.8.3 from the official Ubuntu repo.
There are some failures due to the errors:
```
...no common snapshot or suitable bookmark between sender and receiver...
...
...has been modified since most recent snapshot...
```

That makes sense, but the zrepl daemon shouldn't crash, should it?

The zrepl daemon crashes when the job runs. I'm getting the following error from the zrepl server:
```
020-07-25T19:54:41-04:00 [ERRO][latitude][rpc.data][cyZj$J3Ca$J3Ca.CJwB]: cannot write send stream err="frameconn: shutting down"
panic: end task: 1 active child tasks: end task: task still has active child tasks

goroutine 196966 [running]:
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc000320680, 0xcde000)
        /home/jeremy/go/src/github.com/zrepl/zrepl/daemon/logging/trace/trace.go:221 +0x2f7
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
        /home/jeremy/go/src/github.com/zrepl/zrepl/daemon/logging/trace/trace.go:237 +0x38
github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
        /home/jeremy/go/src/github.com/zrepl/zrepl/daemon/logging/trace/trace_convenience.go:41 +0x37
github.com/zrepl/zrepl/daemon/job.(*PassiveSide).Run.func1(0xdcf780, 0xc0000a3560, 0xdc65a0, 0xc00035e620, 0xc0000a34d0)
        /home/jeremy/go/src/github.com/zrepl/zrepl/daemon/job/passive.go:194 +0x2e7
github.com/zrepl/zrepl/rpc.NewServer.func3(0xdcf780, 0xc0001ce4b0, 0xdc65e0, 0xc00035e600, 0xc0000a34d0)
        /home/jeremy/go/src/github.com/zrepl/zrepl/rpc/rpc_server.go:82 +0xd5
github.com/zrepl/zrepl/rpc/dataconn.(*Server).serveConn(0xc0000a2ba0, 0xc00018eca0)
        /home/jeremy/go/src/github.com/zrepl/zrepl/rpc/dataconn/dataconn_server.go:149 +0x3be
github.com/zrepl/zrepl/rpc/dataconn.(*Server).Serve.func3(0xc0000b8180, 0xc0000a2ba0, 0xc00018eca0)
        /home/jeremy/go/src/github.com/zrepl/zrepl/rpc/dataconn/dataconn_server.go:108 +0x5d
created by github.com/zrepl/zrepl/rpc/dataconn.(*Server).Serve
        /home/jeremy/go/src/github.com/zrepl/zrepl/rpc/dataconn/dataconn_server.go:106 +0x24a
2020-07-25T19:58:55-04:00 [ERRO][latitude][rpc.data][Pt4F$gCWT$gCWT.fzhc]: cannot write send stream err="frameconn: shutting down"
panic: end task: 1 active child tasks: end task: task still has active child tasks

```

My zrepl server config:
```
global:
  monitoring:
    - type: prometheus
      listen: ':9091'
jobs:
- type: source
  name: "latitude"
  serve:
    type: tcp
    listen: ":8888"
    clients: {
      "192.168.1.21" : "daytapod1.jbsnet.xyz"
    }
  filesystems: {
    "rpool<": true,
    "bpool<": true,
  }
  snapshotting:
    type: manual
```

My zrepl client config:
```
global:
  monitoring:
    - type: prometheus
      listen: ':9091'
jobs:
- name: pull_latitude
  type: pull
  connect:
    type: tcp
    address: "192.168.1.8:8888"
  root_fs: "dpool/backups/xyz/jbsnet/latitude/CURRENT"
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: regex
      regex: ".*"
```

The zrepl log on the server side when running the job:
```
Jul 25 20:27:49 daytapod1 zrepl[4760]: 2020-07-25T20:27:49-04:00 [ERRO][_control][job][Mz0V$Mz0V]: control handler error err="already woken up"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$V6JY$V6JY.xT49]: conflict filesystem="rpool/private" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @2020-07-23-03-39-10\n  sorted receiver versions:\n    @2020-03-09-01-03-EDT_sundaynight\n"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$V6JY$V6JY.xT49]: cannot resolve conflict filesystem="rpool/private" problem="no automated way to handle conflict type"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$rL0a$rL0a.ZB4h]: conflict filesystem="rpool/centos7" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @clean\n    @post_setup_pre_install\n    @post_setup_post_install\n    @2020-07-23-03-39-10\n  sorted receiver versions:\n    @post_setup\n"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$rL0a$rL0a.ZB4h]: cannot resolve conflict problem="no automated way to handle conflict type" filesystem="rpool/centos7"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$8iF4$8iF4.Jbk3]: conflict filesystem="rpool/ROOT" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @2020-07-23-03-39-10\n  sorted receiver versions:\n    @2020-03-09-01-03-EDT_sundaynight\n"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$8iF4$8iF4.Jbk3]: cannot resolve conflict filesystem="rpool/ROOT" problem="no automated way to handle conflict type"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$CWru$CWru.x21F]: conflict conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @2020-07-23-03-39-10\n  sorted receiver versions:\n    @2020-03-09-01-03-EDT_sundaynight\n" filesystem="rpool/ROOT/arch/HEAD"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$CWru$CWru.x21F]: cannot resolve conflict filesystem="rpool/ROOT/arch/HEAD" problem="no automated way to handle conflict type"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$l0OH$l0OH.FwGt]: conflict conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @2020-07-23-03-39-10\n  sorted receiver versions:\n    @2020-03-09-01-03-EDT_sundaynight\n" filesystem="rpool/ROOT/ubuntu"
Jul 25 20:28:28 daytapod1 zrepl[4760]: 2020-07-25T20:28:28-04:00 [ERRO][pull_latitude][repl][Mz0V$trzq$l0OH$l0OH.FwGt]: cannot resolve conflict filesystem="rpool/ROOT/ubuntu" problem="no automated way to handle conflict type"
Jul 25 20:28:54 daytapod1 zrepl[4760]: 2020-07-25T20:28:54-04:00 [ERRO][pull_latitude][endpoint][Mz0V$trzq$1hCR$1hCR.PwmF.vvc/.vFgi]: zfs receive failed opts="zfs.RecvOptions{RollbackAndForceRecv:false, SavePartialRecvState:true}" proto_fs="rpool/home/jeremy" err="zfs exited with error: exit status 1\nstderr:\ncannot receive incremental stream: destination dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool/home/jeremy has been modified\nsince most recent snapshot\n" local_fs="dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool/home/jeremy"
Jul 25 20:28:54 daytapod1 zrepl[4760]: 2020-07-25T20:28:54-04:00 [ERRO][pull_latitude][rpc.ctrl][Mz0V$trzq$trzq.bvgt.cJOH]: cannot connect err="dial tcp 192.168.1.8:8888: connect: connection refused"
```

While I could fix up my snapshots to resolve the out of sync state which may work to avoid this crash, I would like to help fix this problem so that the zrepl daemon doesn't crash.

Any help would be greatly appreciated. Let me know if there are any more details I can provide. If I find the time, I will try to set up a test environment that can reliably reproduce this with small test zpools

**Comment by helamonster** [comment]
I did a zfs rollback on the destination server for the dataset:
`dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool/home/jeremy`
To see if I can rule out the logic flow for the "destination dataset has been updated since snapshot" case as causing the crash.
So far it is running OK for that dataset (no crash).
I'll let that finish and report back.

**Comment by problame** [comment]
## Triaging

> That makes sense, but the zrepl daemon shouldn't crash, should it?

No, the daemon should indeed never crash. 

>  `...has been modified since most recent snapshot...`
> ```020-07-25T19:54:41-04:00 [ERRO][latitude][rpc.data][cyZj$J3Ca$J3Ca.CJwB]: cannot write send stream err="frameconn: shutting down"
panic: end task: 1 active child tasks: end task: task still has active child tasks`
```

https://github.com/zrepl/zrepl/blob/10a14a8c5016e8f7d3f145fdfd8ee76af274ede8/rpc/dataconn/dataconn_server.go#L240

=> The crash is likely due to the `has been modified since most recent snapshot` error.

## Reproducer

* Prepare the receiving side to be in sync with the sender but have modified local state
* There needs to be data in flight => sending side snapshot must be so large that the sender is not finished sending before it gets back the `has been modified since most recent snapshot` from the receiving side.
* Do a pull replication
* => crash as originally posted

## Resolution

* The `SendStream.Close()` was not called by `dataconn.Server`, which left the `zfs send` process dangling
* When the source job's `ctx` interceptor closed the task, the dangling `zfs send` was detect by the `trace` package and panicked

I'll push a fix to `problame/develop`, it will show up below and be included in the next `0.3-rc`.

**Comment by problame** [comment]
Fix is up, I'll look into turning this into a platformtest test case to avoid future regressions.

**Comment by problame** [comment]
Regression test is also up.

@helamonster please report back whether the patch fixes your issue.

**Comment by helamonster** [comment]
FYI: After the zfs rollback and running the job again, the zrepl daemon did not crash, so it looks like it is related to that particular error.
I will reproduce this again and then test the patch...

**Comment by helamonster** [comment]
The patched version was able to handle the error without crashing :-)
Thanks for the quick response!
