### ISSUE TITLE
Test failure on Alpine Linux with go1.17

### ISSUE THREAD

**Issue by maxice8** [zrepl/zrepl#514]
```
   	github.com/zrepl/zrepl/transport/ssh	[no test files]
running tcp.testCase{name:"regular ips", config:map[string]string{"192.168.123.234":"ident1", "192.168.20.23":"ident2"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"192.168.123.234":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"ident1"}, "192.168.20.10":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "192.168.20.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"ident2"}}}
running tcp.testCase{name:"full wildcard", config:map[string]string{"0.0.0.0/0":"*", "0::/0":"*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.123.234.24":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"10.123.234.24"}, "fe80::23:42":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"fe80::23:42"}}}
running tcp.testCase{name:"longest prefix matching", config:map[string]string{"10.1.0.0/16":"subnet-one-*", "10.1.0.0/24":"subnet-one-zero-*", "10.1.1.0/24":"subnet-one-one-*", "10.1.2.0/24":"subnet-one-two-*", "10.1.2.3":"specific-host", "fde4:8dba:82e1:1::/64":"v6-64-1-*", "fde4:8dba:82e1:1::1":"v6-48-1-specialhost", "fde4:8dba:82e1:2::/64":"v6-64-2-*", "fde4:8dba:82e1::/48":"v6-48-*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.1.0.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-zero-10.1.0.23"}, "10.1.1.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-one-10.1.1.1"}, "10.1.2.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-two-10.1.2.1"}, "10.1.2.3":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"specific-host"}, "10.1.3.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-10.1.3.1"}, "10.2.1.1":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "fde4:8dba:82e1:1::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-48-1-specialhost"}, "fde4:8dba:82e1:1::2":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-64-1-fde4:8dba:82e1:1::2"}, "fde4:8dba:82e1:23::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-48-fde4:8dba:82e1:23::1"}, "fde4:8dba:82e1:2::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-64-2-fde4:8dba:82e1:2::1"}, "fde4:8dba:82e2::1":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}}}
running tcp.testCase{name:"different prefixes, mixed ipv4 ipv6, with interface ids", config:map[string]string{"10.1.4.0/24":"my-*-server", "192.168.23.0/24":"db-*", "192.168.23.23":"db-twentythree", "192.168.42.0/24":"web-*", "2001:0db8:85a3:0000:0000:8a2e:0370:7334":"aspecifichost", "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth1":"aspecifichost", "fde4:8dba:82e1::/64":"sub64-*", "fe80::/16%eth1":"san-*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.1.2.3":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "10.1.4.5":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"my-10.1.4.5-server"}, "192.168.023.001":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-192.168.23.1"}, "192.168.042.001":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"web-192.168.42.1"}, "192.168.23.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-192.168.23.1"}, "192.168.23.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-twentythree"}, "192.168.42.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"web-192.168.42.1"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"aspecifichost"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"aspecifichost"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth2":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "fde4:8dba:82e1::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"sub64-fde4:8dba:82e1::1"}, "fde4:8dba:82e1::c0a8:1717":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"sub64-fde4:8dba:82e1::c0a8:1717"}, "fe80::23:42%eth1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"san-fe80::23:42-eth1"}, "fe80::23:42%eth2":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}}}
--- FAIL: TestIPMap (0.00s)
    --- FAIL: TestIPMap/different_prefixes,_mixed_ipv4_ipv6,_with_interface_ids (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8982b0]

goroutine 40 [running]:
testing.tRunner.func1.2({0x954fa0, 0xb2f558})
	/usr/lib/go/src/testing/testing.go:1209 +0x290
testing.tRunner.func1(0x1e7e690)
	/usr/lib/go/src/testing/testing.go:1212 +0x27c
panic({0x954fa0, 0xb2f558})
	/usr/lib/go/src/runtime/panic.go:1038 +0x258
github.com/zrepl/zrepl/transport/tcp.TestIPMap.func1(0x1e7e690)
	/home/buildozer/aports/testing/zrepl/src/zrepl-0.4.0/transport/tcp/serve_tcp_ipmap_test.go:183 +0x200
testing.tRunner(0x1e7e690, 0x1e0ae70)
	/usr/lib/go/src/testing/testing.go:1259 +0x104
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1306 +0x39c
FAIL	github.com/zrepl/zrepl/transport/tcp	0.064s
```

**Comment by maxice8** [comment]
and 

```
running tcp.testCase{name:"regular ips", config:map[string]string{"192.168.123.234":"ident1", "192.168.20.23":"ident2"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"192.168.123.234":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"ident1"}, "192.168.20.10":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "192.168.20.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"ident2"}}}
running tcp.testCase{name:"full wildcard", config:map[string]string{"0.0.0.0/0":"*", "0::/0":"*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.123.234.24":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"10.123.234.24"}, "fe80::23:42":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"fe80::23:42"}}}
running tcp.testCase{name:"longest prefix matching", config:map[string]string{"10.1.0.0/16":"subnet-one-*", "10.1.0.0/24":"subnet-one-zero-*", "10.1.1.0/24":"subnet-one-one-*", "10.1.2.0/24":"subnet-one-two-*", "10.1.2.3":"specific-host", "fde4:8dba:82e1:1::/64":"v6-64-1-*", "fde4:8dba:82e1:1::1":"v6-48-1-specialhost", "fde4:8dba:82e1:2::/64":"v6-64-2-*", "fde4:8dba:82e1::/48":"v6-48-*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.1.0.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-zero-10.1.0.23"}, "10.1.1.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-one-10.1.1.1"}, "10.1.2.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-two-10.1.2.1"}, "10.1.2.3":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"specific-host"}, "10.1.3.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"subnet-one-10.1.3.1"}, "10.2.1.1":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "fde4:8dba:82e1:1::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-48-1-specialhost"}, "fde4:8dba:82e1:1::2":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-64-1-fde4:8dba:82e1:1::2"}, "fde4:8dba:82e1:23::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-48-fde4:8dba:82e1:23::1"}, "fde4:8dba:82e1:2::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"v6-64-2-fde4:8dba:82e1:2::1"}, "fde4:8dba:82e2::1":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}}}
running tcp.testCase{name:"different prefixes, mixed ipv4 ipv6, with interface ids", config:map[string]string{"10.1.4.0/24":"my-*-server", "192.168.23.0/24":"db-*", "192.168.23.23":"db-twentythree", "192.168.42.0/24":"web-*", "2001:0db8:85a3:0000:0000:8a2e:0370:7334":"aspecifichost", "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth1":"aspecifichost", "fde4:8dba:82e1::/64":"sub64-*", "fe80::/16%eth1":"san-*"}, expectInitErr:false, expect:map[string]tcp.testCaseExpect{"10.1.2.3":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "10.1.4.5":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"my-10.1.4.5-server"}, "192.168.023.001":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-192.168.23.1"}, "192.168.042.001":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"web-192.168.42.1"}, "192.168.23.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-192.168.23.1"}, "192.168.23.23":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"db-twentythree"}, "192.168.42.1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"web-192.168.42.1"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"aspecifichost"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"aspecifichost"}, "2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth2":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}, "fde4:8dba:82e1::1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"sub64-fde4:8dba:82e1::1"}, "fde4:8dba:82e1::c0a8:1717":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"sub64-fde4:8dba:82e1::c0a8:1717"}, "fe80::23:42%eth1":tcp.testCaseExpect{expectNoMapping:false, expectIdent:"san-fe80::23:42-eth1"}, "fe80::23:42%eth2":tcp.testCaseExpect{expectNoMapping:true, expectIdent:""}}}
--- FAIL: TestIPMap (0.00s)
    --- FAIL: TestIPMap/different_prefixes,_mixed_ipv4_ipv6,_with_interface_ids (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55ecf3f858f2]

goroutine 24 [running]:
testing.tRunner.func1.2({0x55ecf41d3820, 0x55ecf4478ed0})
	/usr/lib/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1212 +0x218
panic({0x55ecf41d3820, 0x55ecf4478ed0})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
github.com/zrepl/zrepl/transport/tcp.TestIPMap.func1(0x0)
	/home/buildozer/aports/testing/zrepl/src/zrepl-0.4.0/transport/tcp/serve_tcp_ipmap_test.go:183 +0x1f2
testing.tRunner(0xc0001036c0, 0xc00022c720)
	/usr/lib/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1306 +0x35a
FAIL	github.com/zrepl/zrepl/transport/tcp	0.012s
```

**Comment by problame** [comment]
Thanks for reporting this!

* What Go version is this? (`go version` or `go env`)
* My quick guess without looking at the code is that the issue is caused by a fix for https://www.bleepingcomputer.com/news/security/go-rust-net-library-affected-by-critical-ip-address-validation-vulnerability/

**Comment by maxice8** [comment]
`go version go1.17.1 linux/amd64` and `go version go1.17 linux/amd64`, also fails on all other arches supported by Alpine Linux `aarch64`, `x86`, `armv7`, `armhf`, `ppc64le`, `s390x`.

**Comment by problame** [comment]
@maxice8 please try the patch linked above.

**Comment by maxice8** [comment]
All green in [CI](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/25356/pipelines)
