### ISSUE TITLE
`snap` job panic related to BandwidthLimit

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#521]
Likely caused by changes made in #506 

```
Oct 01 16:14:56 cstp zrepl[56563]: panic: invalid config`BandwidthLimit` field invalid: BucketCapacity must not be zero                                                   
Oct 01 16:14:56 cstp zrepl[56563]:         panic: end span: span still has active child spans                                                                             
Oct 01 16:14:56 cstp zrepl[56563]: goroutine 38 [running]:                                                                                                                
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/daemon/logging/trace.WithSpan.func2()                                                                           
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/logging/trace/trace.go:341 +0x2ea                                                                  
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()                                                                    
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/logging/trace/trace_convenience.go:40 +0x2e                                                        
Oct 01 16:14:56 cstp zrepl[56563]: panic(0xcee9c0, 0xc000676730)                                                                                                          
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/go1.16.6/src/runtime/panic.go:965 +0x1b9                                                                              
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/endpoint.NewSender(0xf5bbc0, 0xc0003840c0, 0xc0000b2c90, 0x4, 0xc0002c5958, 0x0, 0x0, 0x0, 0xc000068cf8)        
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/endpoint/endpoint.go:68 +0x1ec                                                                            
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/daemon/job.(*SnapJob).doPrune(0xc00039e000, 0xf6e3b8, 0xc0006541b0)                                             
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/job/snapjob.go:179 +0x198                                                                          
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/daemon/job.(*SnapJob).Run(0xc00039e000, 0xf6e3b8, 0xc0001d83c0)                                                 
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/job/snapjob.go:127 +0x329                                                                          
Oct 01 16:14:56 cstp zrepl[56563]: github.com/zrepl/zrepl/daemon.(*jobs).start.func1(0xc0006a4100, 0xf6e3b8, 0xc00022a0f0, 0xf72d18, 0xc00039e000)                        
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/daemon.go:255 +0x15b                                                                               
Oct 01 16:14:56 cstp zrepl[56563]: created by github.com/zrepl/zrepl/daemon.(*jobs).start                                                                                 
Oct 01 16:14:56 cstp zrepl[56563]:         /home/cs/zrepl/zrepl/daemon/daemon.go:251 +0x425                                                                               
Oct 01 16:14:56 cstp systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT                                                                
Oct 01 16:14:56 cstp systemd[1]: zrepl.service: Failed with result 'exit-code'.                                                                                           
```

```
cs@cstp:[~/zrepl/personal_deployment]: cat /etc/zrepl/zrepl.yml                  
global:                                                                          
  logging:                                                                       
    - type: syslog                                                               
      format: human                                                              
      level: debug                                                               
jobs:                                                                            
                                                                                 
- name: snap                                                                     
  type: snap                                                                     
  filesystems: {...}                                                                              
  snapshotting:                                                                  
    type: periodic                                                               
    interval: 10m                                                                
    prefix: zrepl_snap_                                                          
  pruning:                                                                       
    keep:                                                                        
    - type: regex                                                                
      negate: true                                                               
      regex: "^zrepl_snap_.*"                                                    
    - type: grid                                                                 
      regex: "^zrepl_snap_.*"                                                    
      grid: 1x1h(keep=all) | 24x1h | 14x1d                                       

- name: encpush                                                                  
  type: push    
  ...                                                                 
  snapshotting:                                                                  
    type: manual                                                                 
  pruning:                                                                       
    keep_sender:                                                                 
    - type: regex                                                                
      regex: ".*"                                                                
    keep_receiver:                                                               
    - type: regex                                                                
      regex: ".*"                                                                
```

**Comment by problame** [comment]
follow-up errors:

- [ ] specifying `push.send.bandwidth_limt.max = -1` does not work (configcheck error)

workaround:

specify some bandwidth limit, e.g.,

```
  send:                                                                                      
    encrypted: true                                                                          
    bandwidth_limit:                                                                         
      max: "100Gib"
      bucket_capacity: "128 KiB" # token bucket capacity in bytes; defaults to 128KiB        
```
