### ISSUE TITLE
zrepl daemon: panic: end task: 1 active child tasks

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#542]
I'm running zrepl on pfSense 2.4.4-RELEASE-p3 (amd64) with a single source job. A Linux machine is running the associated zrepl pull job. This has been working well mostly, but the daemon on the source machine occasionally crashes.

I'm not sure if this is the same as #411 because this system is running FreeBSD 11.2 but it could be related.

```
[root@pfsense1 /conf]# uname -a
FreeBSD pfsense1.domain.com 11.2-RELEASE-p10 FreeBSD 11.2-RELEASE-p10 #9 4a2bfdce133(RELENG_2_4_4): Wed May 15 18:54:42 EDT 2019     root@buildbot1-nyi.netgate.com:/build/ce-crossbuild-244/obj/amd64/ZfGpH5cd/build/ce-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense  amd64

[root@pfsense1 /conf]# /usr/local/bin/zrepl version
client: zrepl version=v0.4.0 go=go1.15.11 GOOS=freebsd GOARCH=amd64 Compiler=gc
server: error: Post "http://unix/version": dial unix /var/run/zrepl/control: connect: connection refused

[root@pfsense1 /conf]# cat /etc/zrepl/zrepl.yml 
global:
  monitoring:
    - type: prometheus
      listen: ':9091'
jobs:
- type: source
  name: "com.domain.pfsense1"
  serve:
    type: tcp
    listen: ":8888"
    clients: {
      "10.0.0.16" : "backups.domain.com"
    }
  filesystems: {
    "zroot<": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m

[root@pfsense1 /conf]# /usr/local/bin/zrepl daemon
... running ok for about a week, then ...
panic: end task: 1 active child tasks
: end task: task still has active child tasks

goroutine 74536115 [running]:
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc00093db90, 0xee1000)
        /src/daemon/logging/trace/trace.go:249 +0x65e
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
        /src/daemon/logging/trace/trace.go:272 +0x38
github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
        /src/daemon/logging/trace/trace_convenience.go:41 +0x37
github.com/zrepl/zrepl/daemon/job.(*PassiveSide).Run.func1(0xfbe8e0, 0xc00096fd40, 0xfb56a0, 0xc00096d8c0, 0xc00096fcb0)
        /src/daemon/job/passive.go:179 +0x2d5
github.com/zrepl/zrepl/rpc.NewServer.func1.1(0xfbe8e0, 0xc00096fc80, 0xfb5720, 0xc00096d8a0, 0xc00096fcb0)
        /src/rpc/rpc_server.go:56 +0xd5
github.com/zrepl/zrepl/rpc/grpcclientidentity.NewInterceptors.func1(0xfbe8e0, 0xc00096fc80, 0xddae80, 0xc000bdbf80, 0xc00096d740, 0xc00096d760, 0xc00021cba0, 0x49bd46, 0xe175a0, 0xc00096fbc0)
        /src/rpc/grpcclientidentity/authlistener_grpc_adaptor.go:136 +0x464
github.com/zrepl/zrepl/replication/logic/pdu._Replication_ReplicationCursor_Handler(0xe302c0, 0xc00012a240, 0xfbe8e0, 0xc00096fbc0, 0xc000e6d380, 0xc00007ac90, 0xfbe8e0, 0xc00096fbc0, 0xc000032960, 0x14)
        /src/replication/logic/pdu/pdu_grpc.pb.go:226 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017c700, 0xfc7b20, 0xc0009dbb00, 0xc000142600, 0xc00007ade0, 0x14f8000, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1217 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00017c700, 0xfc7b20, 0xc0009dbb00, 0xc000142600, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002bbd90, 0xc00017c700, 0xfc7b20, 0xc0009dbb00, 0xc000142600)
        /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd

```

I am running it like so now and will let update here how that goes:
```
export ZREPL_ACTIVITY_TRACE=/tmp/zrepl.activity.json
cpuset -c -l 0-1 /usr/local/bin/zrepl daemon
```

**Comment by problame** [comment]
Thanks for this bug report.
Could you also set `ZREPL_TRACE_DEBUG_ENABLED=1`? It'll give more helpful debug output next time this occurs.

**Comment by helamonster** [comment]
I just enabled that now and restarted the daemon (which had been running for 4 days without crashing).

**Comment by helamonster** [comment]
Still running with those settings after 13 days, decided to test out 0.5.0 so restarted.

**Comment by JMoVS** [comment]
I had the same issue I think - I noticed that
a) the systemd unit does not have "restart on failure" set and
b) my logs look similar:

```
Oct 24 14:07:57 vmd78397.contaboserver.net systemd[1]: Started zrepl daemon.
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: panic: end task: 1 active child tasks (run daemon with env var ZREPL_TRACE_DEBUG_ENABLED=1 for more details)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: : end task: task still has active child tasks
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: goroutine 991764 [running]:
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc000a862d0)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/daemon/logging/trace/trace.go:249 +0x45a
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/daemon/logging/trace/trace.go:272 +0x2b
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/daemon/logging/trace/trace_convenience.go:41 +0x2e
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/daemon/job.(*PassiveSide).Run.func1({0xe42bd8, 0xc0002f3710}, {0xe3a690, 0xc000043e40}, 0xc0002f3740)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/daemon/job/passive.go:179 +0x218
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/rpc.NewServer.func1.1({0xe42bd8, 0xc0002f3710}, {0xe3a6e0, 0xc000043e20}, 0xbe4a80)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/rpc/rpc_server.go:56 +0xae
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/rpc/grpcclientidentity.NewInterceptors.func1({0xe42bd8, 0xc0002f3650}, {0xc7b520, 0xc000969900}, 0xc000043ce0, 0>
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/rpc/grpcclientidentity/authlistener_grpc_adaptor.go:136 +0x3be
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: github.com/zrepl/zrepl/replication/logic/pdu._Replication_ReplicationCursor_Handler({0xcd6da0, 0xc00050a200}, {0xe42bd8, 0xc0002f3650},>
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /src/replication/logic/pdu/pdu_grpc.pb.go:240 +0x138
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c8000, {0xe51700, 0xc0007e6180}, 0xc0005bd000, 0xc000099110, 0x13dbc40, 0x0)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1217 +0xc8f
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: google.golang.org/grpc.(*Server).handleStream(0xc0001c8000, {0xe51700, 0xc0007e6180}, 0xc0005bd000, 0x0)
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1540 +0xa2a
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:878 +0x98
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Oct 29 17:35:33 vmd78397.contaboserver.net zrepl[624742]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:876 +0x294
Oct 29 17:35:33 vmd78397.contaboserver.net systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

```

**Comment by JMoVS** [comment]
it's been happening quite a few times now in the last weeks
