### ISSUE TITLE
zrepl 0.2.1 and 0.3.0 dumps core when run in systemd unit

### ISSUE THREAD

**Issue by rugubara** [zrepl/zrepl#698]
At some point, I can no longer start the zrepl.service. Both configcheck and daemon invocations dump core.  
When I run these commands from the root shell they both succeed

What is the recommended way to troubleshoot this situation?

```
PF16W6Y2 /etc/systemd/system systemctl status zrepl.service
× zrepl.service - zrepl daemon
     Loaded: loaded (/usr/lib/systemd/system/zrepl.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/zrepl.service.d
             └─override.conf
     Active: failed (Result: core-dump) since Tue 2023-04-18 14:55:04 MSK; 25min ago
   Duration: 298ms
       Docs: https://zrepl.github.io
    Process: 2729903 ExecStart=/usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon (code=dumped, signal=SYS)
   Main PID: 2729903 (code=dumped, signal=SYS)

апр 18 14:55:04 PF16W6Y2 systemd[1]: Started zrepl.service.
апр 18 14:55:04 PF16W6Y2 systemd[1]: zrepl.service: Main process exited, code=dumped, status=31/SYS
апр 18 14:55:04 PF16W6Y2 systemd[1]: zrepl.service: Failed with result 'core-dump'.
```

**Comment by rugubara** [comment]
I built it from source (as I run Gentoo). The ebuild script can be found here: https://github.com/rugubara/overlay/tree/master/sys-fs/zrepl 
I confirm that this problem happens on 2 my hosts

**Comment by rugubara** [comment]
I use go 1.20.3 if this matters (I think it does). Here is the gdb output from the coredump:
```
PF16W6Y2 /etc/systemd/system # coredumpctl -1 debug
           PID: 4014289 (zrepl)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 31 (SYS)
     Timestamp: Tue 2023-04-18 23:11:42 MSK (43s ago)
  Command Line: /usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon
    Executable: /usr/bin/zrepl
 Control Group: /system.slice/zrepl.service
          Unit: zrepl.service
         Slice: system.slice
       Boot ID: a2b8730cd1664f639c4860d8fb4d2893
    Machine ID: 2c7f8e45cda78c341d153c0f5bc203b4
      Hostname: PF16W6Y2
       Storage: /var/lib/systemd/coredump/core.zrepl.0.a2b8730cd1664f639c4860d8fb4d2893.4014289.1681848702000000.zst (present)
  Size on Disk: 2.3M
       Message: Process 4014289 (zrepl) of user 0 dumped core.

GNU gdb (Gentoo 13.1.90_p20230325 vanilla) 13.1.90.20230325-git
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/zrepl...
[New LWP 4014289]
[New LWP 4014290]
[New LWP 4014292]
[New LWP 4014293]
[New LWP 4014291]
[New LWP 4014294]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon'.
Program terminated with signal SIGSYS, Bad system call.
#0  runtime/internal/syscall.Syscall6 () at /usr/lib/go/src/runtime/internal/syscall/asm_linux_amd64.s:36
36	        CMPQ	AX, $0xfffffffffffff001
[Current thread is 1 (Thread 0x7f9eded04740 (LWP 4014289))]
warning: File "/usr/lib/go/src/runtime/runtime-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/go/src/runtime/runtime-gdb.py
line to your configuration file "/root/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
```

**Comment by rugubara** [comment]
I continue my journey into this mistery and I could identify that the offending syscall is setrlimit:
```
(gdb) bt
#0  runtime/internal/syscall.Syscall6 () at /usr/lib/go/src/runtime/internal/syscall/asm_linux_amd64.s:36
#1  0x0000558a9caf57b3 in syscall.RawSyscall6 (num=160, a1=7, a2=94053822584782, a3=7, a4=824634198688, a5=0, a6=0,
    r1=<optimized out>, r2=<optimized out>, errno=<optimized out>)
    at /usr/lib/go/src/runtime/internal/syscall/syscall_linux.go:38
#2  0x0000558a9cb742db in syscall.RawSyscall (trap=160, a1=7, a2=94053822584782, a3=7, r1=<optimized out>,
    r2=<optimized out>, err=<optimized out>) at /usr/lib/go/src/syscall/syscall_linux.go:62
#3  0x0000558a9cb730cf in syscall.Setrlimit (resource=<optimized out>, rlim=<optimized out>, err=...)
    at /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1326
#4  0x0000558a9cbe158e in os.init.1 () at /usr/lib/go/src/os/rlimit.go:30
#5  0x0000558a9cb39ea8 in runtime.doInit (t=0x558a9d997680 <os.[inittask]>) at /usr/lib/go/src/runtime/proc.go:6506
#6  0x0000558a9cb39df1 in runtime.doInit (t=0x558a9d995860 <fmt.[inittask]>) at /usr/lib/go/src/runtime/proc.go:6483
#7  0x0000558a9cb39df1 in runtime.doInit (t=0x558a9d9959e0 <github.com/zrepl/zrepl/cli.[inittask]>)
    at /usr/lib/go/src/runtime/proc.go:6483
#8  0x0000558a9cb39df1 in runtime.doInit (t=0x558a9d991900 <main.[inittask]>) at /usr/lib/go/src/runtime/proc.go:6483
#9  0x0000558a9cb2c753 in runtime.main () at /usr/lib/go/src/runtime/proc.go:233
#10 0x0000558a9cb5fa41 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:1598
#11 0x0000000000000000 in ?? ()
```

also I think that it has something to do with Go package itself. 
The version 0.2.1 that I used to run successfully was built on 2020-06-20T16:33:08 and I never rebuilt it since then. 
the version of Go was dev-lang/go-1.14.4. 

I'm not a Go developer. Can you please advise what can be done about it? Where to look for?

**Comment by rugubara** [comment]
version 0.6.0 works as expected, sorry for distraction.
